backend = "fastresize"
palette = "dark16"
check_contrast = true

[templates]

waybar.template = "waybar.css.j2"
waybar.target = "~/.config/waybar/style.css"

waybar_config.template = "waybar-config.jsonc.j2"
waybar_config.target = "~/.config/waybar/config.jsonc"

swaync.template = "swaync.css.j2"
swaync.target = "~/.config/swaync/style.css"

wlogout.template = "wlogout.css.j2"
wlogout.target = "~/.config/wlogout/style.css"

hypr.template = "hypr-colors.lua.j2"
hypr.target = "~/.config/hypr/colors.lua"

kitty.template = "kitty-colors.conf.j2"
kitty.target = "~/.config/kitty/colors.conf"

cava.template = "cava-colors.j2"
cava.target = "~/.config/cava/themes/generated"

rofi.template = "rofi-colors.rasi.j2"
rofi.target = "~/.config/rofi/theme-generated.rasi"

env.template = "wallust-env.j2"
env.target = "~/.config/wallust/env"

browser_colors.template = "browser-colors.css.j2"
browser_colors.target = "~/.config/wallust/browser-colors.css"

chromium_theme.template = "chromium-theme.json.j2"
chromium_theme.target = "~/.config/wallust/chromium-theme.json"

wallpaper_grid.template = "wallpaper-grid.rasi.j2"
wallpaper_grid.target = "~/.config/rofi/themes/wallpaper-grid.rasi"

power.template = "power.rasi.j2"
power.target = "~/.config/rofi/themes/power.rasi"

launcher.template = "launcher.rasi.j2"
launcher.target = "~/.config/rofi/themes/launcher.rasi"

hyprlock.template = "hyprlock.conf.j2"
hyprlock.target = "~/.config/hypr/hyprlock.conf"

icon_lock.template = "lock.svg.j2"
icon_lock.target = "~/.config/rofi/icons/lock.svg"

icon_logout.template = "logout.svg.j2"
icon_logout.target = "~/.config/rofi/icons/logout.svg"

icon_sleep.template = "sleep.svg.j2"
icon_sleep.target = "~/.config/rofi/icons/sleep.svg"

icon_reboot.template = "reboot.svg.j2"
icon_reboot.target = "~/.config/rofi/icons/reboot.svg"

icon_shutdown.template = "shutdown.svg.j2"
icon_shutdown.target = "~/.config/rofi/icons/shutdown.svg"

icon_cancel.template = "cancel.svg.j2"
icon_cancel.target = "~/.config/rofi/icons/cancel.svg"

icon_static.template = "static.svg.j2"
icon_static.target = "~/.config/rofi/icons/static.svg"

icon_live.template = "live.svg.j2"
icon_live.target = "~/.config/rofi/icons/live.svg"

kdeglobals.template = "kdeglobals.j2"
kdeglobals.target = "~/.config/kdeglobals"

colorscheme_bitzdots.template = "bitzdots.colors.j2"
colorscheme_bitzdots.target = "~/.local/share/color-schemes/bitzdots.colors"

qt6ct.template = "qt6ct.conf.j2"
qt6ct.target = "~/.config/qt6ct/qt6ct.conf"
