-- Auto-generated by matugen — DO NOT EDIT
-- Used by appearance.lua via require("colors")

local colors = {
    background = "{{colors.background.default.hex_stripped}}",
    foreground = "{{colors.on_surface.default.hex_stripped}}",
    primary = "{{colors.primary.default.hex_stripped}}",
    secondary = "{{colors.secondary.default.hex_stripped}}",
    tertiary = "{{colors.tertiary.default.hex_stripped}}",
    surface = "{{colors.surface.default.hex_stripped}}",
    error = "{{colors.error.default.hex_stripped}}",
    color0 = "{{colors.surface_container_highest.default.hex_stripped}}",
    color1 = "{{colors.error.default.hex_stripped}}",
    color2 = "{{colors.tertiary.default.hex_stripped}}",
    color3 = "{{colors.primary.default.hex_stripped}}",
    color4 = "{{colors.secondary.default.hex_stripped}}",
    color5 = "{{colors.inverse_primary.default.hex_stripped}}",
    color6 = "{{colors.on_tertiary_container.default.hex_stripped}}",
    color7 = "{{colors.on_surface_variant.default.hex_stripped}}",
    color8 = "{{colors.outline.default.hex_stripped}}",
    color9 = "{{colors.on_error_container.default.hex_stripped}}",
    color10 = "{{colors.on_tertiary_container.default.hex_stripped}}",
    color11 = "{{colors.on_primary_container.default.hex_stripped}}",
    color12 = "{{colors.on_secondary_container.default.hex_stripped}}",
    color13 = "{{colors.primary.default.hex_stripped}}",
    color14 = "{{colors.tertiary.default.hex_stripped}}",
    color15 = "{{colors.on_surface.default.hex_stripped}}",
}

return colors
